"""Convert between reviewable SQL source and the packaged icon database."""

import argparse
import contextlib
import sqlite3
import tempfile
from pathlib import Path

DATA_DIR = Path(__file__).parent / "src" / "lucide" / "data"
SQL_SOURCE = DATA_DIR / "lucide-icons.sql"
DATABASE = DATA_DIR / "lucide-icons.db"


def _identifier(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def export_database(database: Path, source: Path) -> None:
    """Export sorted schema and rows, excluding the volatile build timestamp."""
    lines = [
        "-- Generated by build_support.py export; do not edit by hand.",
        "BEGIN TRANSACTION;",
    ]
    with contextlib.closing(
        sqlite3.connect(f"{database.resolve().as_uri()}?mode=ro", uri=True)
    ) as conn:
        tables = conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE type = 'table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        ).fetchall()
        for name, schema in tables:
            lines.append(schema + ";")
            table = _identifier(name)
            columns = [row[1] for row in conn.execute(f"PRAGMA table_info({table})")]
            quoted = ", ".join(_identifier(column) for column in columns)
            values = ", ".join(f"quote({_identifier(column)})" for column in columns)
            # Creation time describes a generated artifact, not the icon content.
            where = " WHERE key != 'created_at'" if name == "metadata" else ""
            for row in conn.execute(
                f"SELECT {values} FROM {table}{where} ORDER BY {quoted}"
            ):
                lines.append(f"INSERT INTO {table} VALUES({','.join(row)});")
        for (schema,) in conn.execute(
            "SELECT sql FROM sqlite_master WHERE type = 'index' AND sql IS NOT NULL "
            "ORDER BY name"
        ):
            lines.append(schema + ";")
    lines.append("COMMIT;")
    source.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def restore_database(source: Path, database: Path) -> None:
    """Reconstruct and validate SQLite, replacing the destination only on success."""
    database.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        dir=database.parent, suffix=".db", delete=False
    ) as tmp:
        temporary = Path(tmp.name)
    try:
        with contextlib.closing(sqlite3.connect(temporary)) as conn:
            conn.executescript(source.read_text(encoding="utf-8"))
            if conn.execute("PRAGMA integrity_check").fetchone() != ("ok",):
                raise ValueError("Reconstructed icon database failed integrity_check")
            if not conn.execute("SELECT 1 FROM icons LIMIT 1").fetchone():
                raise ValueError("Reconstructed icon database contains no icons")
            if not conn.execute(
                "SELECT value FROM metadata WHERE key = 'version'"
            ).fetchone():
                raise ValueError("Reconstructed icon database has no version")
            if conn.execute(
                "SELECT 1 FROM icon_aliases LEFT JOIN icons "
                "ON icons.name = icon_aliases.name WHERE icons.name IS NULL LIMIT 1"
            ).fetchone():
                raise ValueError(
                    "Reconstructed icon database contains dangling aliases"
                )
        temporary.chmod(0o644)
        temporary.replace(database)
    finally:
        temporary.unlink(missing_ok=True)


def main() -> None:
    """Export the updated database or restore the local development database."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("export", "restore"))
    args = parser.parse_args()
    if args.action == "export":
        export_database(DATABASE, SQL_SOURCE)
    else:
        restore_database(SQL_SOURCE, DATABASE)


if __name__ == "__main__":
    main()
